services:
  pysunlight:
    container_name: pysunlight
    build:
      context: "./Context"
    env_file:
      - .env
    volumes:
      - ${INPUTS_FOLDER}:/inputs
      - ${OUTPUTS_FOLDER}:/outputs
